### PR TITLE
Build macOS binaries

### LINKED ISSUE #64: Support other distributions
I am unable to run my pipeline locally with the new Go builds since it is only built for Linux. It would be nice if the releases were cross-compiled and the plugin detected which needed to be loaded.

### PR DESCRIPTION
**Pull request by runlevel5**
Fixes #64

### CODE REVIEW

**Comment by adikari** [comment]
@runlevel5 there seems to be issue with https://github.com/chronotc/monorepo-diff-buildkite-plugin/blob/master/Makefile#L34

When we are building multiple binaries each binary gets built then cleaned up on the next run. So we end up with only 1 binary in the end. While you are at it, could you fix this too?

**Comment by runlevel5** [comment]
@adikari let me fix that issue for you

**Comment by runlevel5** [comment]
@adikari please squash & merge this PR

**Comment by runlevel5** [comment]
@adikari good to go

**Comment by adikari** [comment]
@runlevel5 ping me when fixed.

**Pull request merged**
