### PR TITLE
add support to disable interpolation on pipeline upload

### PR DESCRIPTION
**Pull request by pmenglund**
This fixes https://github.com/chronotc/monorepo-diff-buildkite-plugin/issues/34

I've never used bats before, so please take a close look at it...

### CODE REVIEW

**Comment by pmenglund** [comment]
ping @chronotc

**Review by adikari — APPROVED** [review]

**Comment by adikari** [comment]
Thanks for contributing

**Comment by adikari** [comment]
@pmenglund the tests you added are failing. Also looking at the tests I am not clear what what you are testing. I would appreciate if you could clarify that. Also how did you run your tests?

**Comment by pmenglund** [comment]
@adikari I've never used bats before, so it isn't unlikely that I got it wrong. I ran it too long ago to remember, but if I recall correctly, I just ran `docker-compose run --rm tests`. I might only be asserting the value of the stub 🤦

**Comment by adikari** [comment]
@pmenglund all good. I have removed the tests for now so that build can go back to green.

**Comment by adikari** [comment]
@all-contributors please add @pmenglund for code and test

**Pull request merged**
