### PR TITLE
Build binary for linux-arm64

### PR DESCRIPTION
**Pull request by runlevel5**
## Changes

* Add `ARCH` parameter which takes in `amd64` and `arm64` as value
* Modify GitHub Action to build binary for both architectures

### CODE REVIEW

**Comment by adikari** [comment]
@runlevel5 i will go through this next week. Thanks for the PR

**Comment by adikari** [comment]
@runlevel5 Before we can release a new version, there are few chores we need to do. I will do that when I can (hopefully this week). If you want to speed up things here are the remaining chores:

1. Update the readme and examples to use next release version. (else plugin lint will fail)
2. Update the changelog to include the next release.
3. Update github action to build and upload both binaries to github release. https://github.com/chronotc/monorepo-diff-buildkite-plugin/blob/master/.github/workflows/publish.yml

You can check out How to Release section in the Contributing Guide. 

Thanks.

**Comment by adikari** [comment]
@runlevel5 sure. Can you also rebase from master before pushing your changes? I have merged your other PR and fixed the GitHub actions.

**Comment by runlevel5** [comment]
@adikari it is now good

**Comment by adikari** [comment]
@runlevel5 sure. I will merge this now.

**Pull request merged**
