### PR TITLE
Support for environment variables globally in the pipeline

### PR DESCRIPTION
**Pull request by jullianoacqio**

### CODE REVIEW

**Comment by adikari** [comment]
@jullianoacqio sorry for delay. I am currently working on go rewrite of the plugin as currently with Bash it's really hard to maintain. I will include this functionality in the alpha release. I will let you know when it's ready.

**Comment by jullianoacqio** [comment]
@adikari Excellent.
We are interested in this project, and if you think we can contribute, we are available.

**Comment by adikari** [comment]
@jullianoacqio thank you. I am sure there will be plenty of things to be involved in. I am happy for you to pick up any bugs or issues or anything you think might improve the plugin.
I will ping you once the go version is ready. I would appreciate if you could help with testing before the release?

**Comment by adikari** [comment]
#47 includes this feature

**Comment by adikari** [comment]
Version 2.0.3 includes this functionality.

**Comment by adikari** [comment]
@all-contributors please add @jullianoacqio for code and test

**Pull request closed without merging**
