### PR TITLE
Support for environment variables globally in the pipeline

### PR DESCRIPTION
**Pull request by jullianoacqio**
This PR adds the ability to pass global environment variables to the pipeline.

```yaml
env: 
    MESSAGE: hello world
step:
  - commands:
      - "echo $MESSAGE"
...
```

### CODE REVIEW

**Comment by jullianoacqio** [comment]
ping @adikari

**Comment by adikari** [comment]
@jullianoacqio i will go through this next week. Thank you.

**Comment by adikari** [comment]
@jullianoacqio Seems like this breaks the pipeline upload. Could you please fix this and reopen the PR?

image

**Comment by jullianoacqio** [comment]
@adikari I can't simulate the error you encountered. In fact, the execution of the project on my buildkite account has a different behavior.
However, with regard to the pipeline generation step, it was built correctly. I enabled `DEBUG` and that was the result.
image

for all intents and purposes, I am uploading another pull request in which the `ENV` key will be created only when necessary.

**Comment by adikari** [comment]
@jullianoacqio the pipeline that failed is inside the e2e folder. Please check the line 102 on the screenshot I posted. Could you try to run that config and see what you get? I had some that uploaded fine but 2 that didn't upload.

**Comment by jullianoacqio** [comment]
I can't run any script from the e2e folder correctly. All give pipeline upload errors, as shown in the screenshot.
What I did to simulate the project in my Buildkite account was just to create a pipeline that uploads the pipeline that exists in the project.

What else can I do to get the same execution as you. I see that in your screen capture there are some different steps from the one in the project pipeline?

**Comment by adikari** [comment]
Please give me some time and I will look into this properly and suggest you how to replicate it.

**Pull request merged**
